# # # TupleD = ("london","usa","australia,canada,newzealand")
# # # print(TupleD)
# # # print(TupleD[0])
# # # print(TupleD[2])
# # # print(TupleD[-1])
# # # print(TupleD[-2])






# # # tupleD=(11,22,33,44,55)
# # a,b,c,d,e=tupleD
# # print(a)
# # print(b)
# # print(c)
# # print(d)
# # print(e)




# # num = (1,2,3)
# # l = list(num)
# # l[1] = 20
# # num = tuple(l)

# # print(num, "This Value is ch")


# tup = (1,2,3,4,5)
# print(tup)

# om = list(tup)
# print(om)

# del om[2]
# print(om, ", 3")

# tup = tuple(om)
# print (tup, "last")
